#########################################
# CONFIG FOR FOLDED SNR PLOTTING SCRIPT #
#########################################

# Observation Details ------>
src_ra_dec: "07:42:48.9513465 -28:22:44.30356" # RA and DEC of the source from ATNF PSR Catalogue (e.g., "07:42:48.9513465 -28:22:44.30356")
normal: True              # Normalized SNR map plot - Folded, Simulated and Residual
saveif: True              # For saving folded SNR map data in a csv file

# Ellipse parameters for beam pattern plot ------>
# (from beam simulation) 
ellipse_a: 20.32        # Semi-major axis (in arcseconds)
ellipse_b: 7.92         # Semi-minor axis (in arcseconds)
ellipse_angle: -131.56  # Angle of the ellipse in degrees 

# Simulation Beam Details ------>
# Enter the log file auto_tile-<Date>-<Time>.log NOTE - Time should be the time immediate before the scan time. Get the "Selected tiling <sel_beam>" from the log file
sel_beam: "g0"
#log_file: "/lustre_archive/spotlight/data/TEST_20250721_031926/BMSTR_SIM/auto_tile-26-07-25-144858.log"
radec_offset: "0,0" # Offset- (ra,dec) in arc sec
make_beam_file: "/lustre_archive/spotlight/data/TEST_20250726_142132/BMSTR_SIM/make_beam-26-07-25-144858.pkl"

# Paths for data and output ------>
header_dir_path: "/lustre_data/spotlight/data/TEST_20250726_142132/BeamData/J0742-2822_20250726_145001"               # Path to the directory containing the header files (ahdr files)
pfd_dir_path: "/lustre_data/spotlight/data/TEST_20250726_142132/FilData/J0742-2822_20250726_145001/FOLDING_OUTPUTS"   # Path to the directory containing the PRESTO's folding output (pfd files)
output_dir_path: "/lustre_data/spotlight/data/TEST_20250726_142132/FilData/J0742-2822_20250726_145001"                # Path to the directory where the snr plot and data will be saved

##########################################################
# CONFIG FOR SNR MAPS FROM RAW DATA, STAGE-WISE SNR MAPS #
##########################################################

# Observation details ----->
scan_id: "J0534+2200_20250420_193105"
observation_path: "/lustre_data/spotlight/data/48_051_20250420_191846" # Path to overall observation directory
dm_thresh: 10
time_thresh: 0.01

# Provide the .h5 file (stored in FRBPipeData) of the verified burst below (candidate selection is done based on this DM and ToA)
cand_h5file_path: "/lustre_data/spotlight/data/48_051_20250420_191846/FRBPipeData/J0534+2200_20250420_193105/BM127/MJD60785.5839806_T3.6752589_DM56.70000_SNR33.81694.h5"

# Provide the current RA, DEC of the source being observed (from ATNF, in the below format)
cand_ra_dec: "05h34m31.93357s +22d00m52.1927s"

# MAIN OUTPUT DIRECTORY for RAW/STAGEWISE SNR MAPS -- all o/p files get stored here -- change for every scan!
output_dir: "/lustre_archive/spotlight/vyaas/snr_maps/outputs/J0534+2200_20250420_193105"

log_level: "DEBUG"
